INSERT INTO ARTICLE(TITLE,CONTENT, CREATED_AT, UPDATED_AT)VALUES('제목_1', '내용_1', NOW(), NOW())
INSERT INTO ARTICLE(TITLE,CONTENT, CREATED_AT, UPDATED_AT)VALUES('제목_2', '내용_2', NOW(), NOW())
INSERT INTO ARTICLE(TITLE,CONTENT, CREATED_AT, UPDATED_AT)VALUES('제목_3', '내용_3', NOW(), NOW())